version: "3.8"

services:
  consumer:
    build:
      context: ./consumer
    container_name: kafka-consumer
    environment:
      BOOTSTRAP_SERVERS: 192.168.1.214:9093
      TOPIC: sensor.raw
      GROUP_ID: kubik-consumer
      AUTO_OFFSET_RESET: earliest
      PYTHONUNBUFFERED: 1
    tty: true
    stdin_open: true

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: pc1
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 192.168.1.214:9093
      KAFKA_CLUSTERS_0_ZOOKEEPER: pc-kafka:2181
    extra_hosts:
      - "pc-kafka:192.168.1.214"
    restart: unless-stopped