version: "3.8"

services:
  web:
    image: nginx:alpine
    container_name: pc3_web
    ports:
      - "8085:80"
    volumes:
      # monta a pasta toda (index.html + style.css + o que vier)
      - ./WEB:/usr/share/nginx/html:ro
      # mantém o nginx.conf na pasta de configs
      # mantém o nginx.conf na pasta de configs
      - ./WEB/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  bridge:
    build:
      context: .
      dockerfile: Dockerfile.bridge
    container_name: pc3_bridge
    ports:
      - "3001:3001"
    environment:
      - KAFKA_BROKERS=192.168.21.227:9093
    restart: unless-stopped
