version: "3.8"

services:
  web:
    image: nginx:alpine
    container_name: pc3_web
    ports:
      - "8080:80"
    volumes:
      # monta a pasta toda (index.html + style.css + o que vier)
      - ./WEB:/usr/share/nginx/html:ro
      # mant√©m o nginx.conf na pasta de configs
      - ./WEB/nginx.conf:/etc/nginx/conf.d/default.conf:ro
